import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import Sidebar from "@/app/components/Sidebar";
import Header from './Header';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`h-full ${geistSans.variable} ${geistMono.variable}`}>
        <div className="min-h-screen">
          {/* Header - Fixed at the top */}
          <header className="fixed top-0 left-0 right-0 h-16 bg-white border-b border-gray-200 z-50">
            <Header />
          </header>

          {/* Main container - Adjusted to account for fixed header */}
          <div className="pt-16 flex min-h-screen">
            <SidebarProvider>
              {/* Sidebar - Full height minus header */}
              <div className="h-[calc(100vh-4rem)] sticky top-16">
                <Sidebar />
              </div>
              
              {/* Main Content */}
              <main className="flex-1 relative">
                <div className="sticky top-20 left-4 z-40 md:hidden">
                  <SidebarTrigger />
                </div>
                <div className="p-4">
                  {children}
                </div>
              </main>
            </SidebarProvider>
          </div>
        </div>
      </body>
    </html>
  );
}